GET localhost:8029/records

###

GET localhost:8029/records?size=10&sortKey=topic

###

POST localhost:8029/records/filter
Accept: application/json
Content-Type: application/json

{
  "filters": [
    {
      "key": "topic",
      "value": "main-topic.kafka-listener.DLT",
      "operator": "EQUALS"
    }
  ]
}
