spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: kafka-triage
  datasource:
    url: jdbc:postgresql://localhost:5432/kafka-triage
    username: rootuser
    password: rootpass
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

