spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: kafka-triage
  sql:
    init:
      mode: always
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/kafka-triage
    username: rootuser
    password: rootpass
  flyway:
    url: jdbc:postgresql://localhost:5432/kafka-triage
    user: rootuser
    password: rootpass

