server:
  port: 8029

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:29092
  datasource:
    url: jdbc:postgresql://localhost:5432/kafka-triage
    username: rootuser
    password: rootpass

logging:
  level:
    com.mnijdam.kafkatriage: DEBUG
    org.jooq.tools.LoggerListener: DEBUG
#    root: debug